---
- name: Read token from file
  slurp:
    src: /tmp/token
  register: k3s_token_raw

- name: Decode token
  set_fact:
    k3s_token: "{{ k3s_token_raw.content | b64decode | trim }}"

- name: Wait for API server to become reachable
  shell: |
    timeout 60 bash -c '
      until curl -k https://{{ hostvars["node1"].ansible_host }}:6443/ping; do
        sleep 3;
      done'
  changed_when: false

- name: Check if K3s agent is already installed
  stat:
    path: /etc/systemd/system/k3s-agent.service
  register: k3s_agent_installed

- name: Install K3s agent
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_URL=https://{{ hostvars['node1'].ansible_host }}:6443 \
    K3S_TOKEN={{ k3s_token }} \
    INSTALL_K3S_EXEC="--node-ip={{ ansible_host }}" \
    sh -
  args:
    executable: /bin/bash
  when: not k3s_agent_installed.stat.exists

- name: Ensure k3s-agent service is enabled and running
  systemd:
    name: k3s-agent
    enabled: true
    state: started