---
- name: Check if Helm is already installed
  stat:
    path: /usr/local/bin/helm
  register: helm_installed

- name: Install Helm
  shell: |
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  when: not helm_installed.stat.exists