apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/santiagovarela86/lab-cluster-gitops.git
        revision: HEAD
        directories:
          - path: argo-apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/santiagovarela86/lab-cluster-gitops.git
        targetRevision: HEAD
        path: '{{path}}'        
        kustomize:
          enableHelm: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true