---
- name: Check if python3-pip is already installed
  ansible.builtin.shell: |
    dpkg -s python3-pip
  register: pip_check
  failed_when: false
  changed_when: false

- name: Check if kubernetes Python client is installed
  ansible.builtin.shell: |
    python3 -c "import kubernetes" >/dev/null 2>&1
  register: k8s_python_check
  failed_when: false
  changed_when: false

- name: Ensure python3-pip is installed (only if missing)
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes
  when: pip_check.rc != 0

- name: Install kubernetes Python client (only if missing)
  ansible.builtin.pip:
    name: kubernetes
    executable: pip3
  when: k8s_python_check.rc != 0