---
- name: Check if K3s is already installed
  stat:
    path: /etc/rancher/k3s/k3s.yaml
  register: k3s_installed

- name: Install K3s on master
  shell: |
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_EXEC="--tls-san {{ ansible_host }} --node-ip {{ ansible_host }} --write-kubeconfig-mode=644 --disable traefik" \
    sh -
  args:
    executable: /bin/bash
  when: not k3s_installed.stat.exists

- name: Wait for API server on master to become reachable
  shell: |
    timeout 60 bash -c '
      until curl -k https://{{ ansible_host }}:6443/ping; do
        sleep 3;
      done'
  changed_when: false