---
- name: Create monitoring namespace
  shell: kubectl create namespace monitoring --kubeconfig=/etc/rancher/k3s/k3s.yaml
  register: ns_created
  failed_when: false
  changed_when: "'created' in ns_created.stdout"

- name: Add Prometheus Helm repo
  shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && helm repo update
  args:
    creates: /usr/local/bin/helm_repo_added_flag
  register: helm_add_output
  changed_when: "'added' in helm_add_output.stdout"

# - name: Install kube-prometheus-stack
#   shell: >
#     helm upgrade --install prometheus prometheus-community/kube-prometheus-stack
#     --namespace monitoring
#     --set grafana.service.type=NodePort
#     --set grafana.service.nodePort=30000
#     --set grafana.adminPassword={{ grafana_admin_password }}
#     --set prometheus.service.type=ClusterIP
#     --kubeconfig=/etc/rancher/k3s/k3s.yaml
#   register: helm_install_output
#   changed_when: "'Release \"prometheus\" has been upgraded' in helm_install_output.stdout or 'Release \"prometheus\" has been installed' in helm_install_output.stdout"