---
- name: Check if ArgoCD is installed
  kubernetes.core.k8s_info:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    api_version: apps/v1
    kind: Deployment
    name: argocd-server
    namespace: argocd
  register: argocd_state
  failed_when: false
  changed_when: false

- name: Set ArgoCD installed fact
  set_fact:
    argocd_installed: "{{ argocd_state.resources is defined and argocd_state.resources | length > 0 }}"

- name: Ensure ArgoCD namespace exists
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd

- name: Install ArgoCD if not installed
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    namespace: argocd
    state: present
    src: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  when: not argocd_installed

- name: Wait for all ArgoCD pods to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: argocd
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  register: argocd_pods
  until: argocd_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length == argocd_pods.resources | length
  retries: 30
  delay: 10

- name: Load ArgoCD apps manifest from file
  set_fact:
    argocd_manifest: "{{ lookup('file', './roles/argocd/files/argo-apps.yaml') | from_yaml }}"

- name: Apply ArgoCD apps manifest
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ argocd_manifest }}"
    apply: true