---
- name: Wait until node joins the cluster
  kubernetes.core.k8s_info:
    kubeconfig: /tmp/kubeconfig.yaml
    kind: Node
    name: "{{ inventory_hostname }}"
  register: node_check
  failed_when: false
  retries: 10
  delay: 6
  until: node_check.resources is defined and node_check.resources | length > 0
  changed_when: false

- name: Get existing labels for worker node
  kubernetes.core.k8s_info:
    kubeconfig: /tmp/kubeconfig.yaml
    kind: Node
    name: "{{ inventory_hostname }}"
  register: existing_labels
  changed_when: false

- name: Label worker node if not labeled
  kubernetes.core.k8s:
    kubeconfig: /tmp/kubeconfig.yaml
    kind: Node
    name: "{{ inventory_hostname }}"
    api_version: v1
    definition:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
    merge_type: merge