---
- name: Check if K3s is already installed
  stat:
    path: /etc/rancher/k3s/k3s.yaml
  register: k3s_installed

- name: Install K3s on master
  shell: |
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_EXEC="--tls-san {{ ansible_host }} --node-ip {{ ansible_host }} --write-kubeconfig-mode=644 --disable traefik" \
    sh -
  args:
    executable: /bin/bash
  when: not k3s_installed.stat.exists

- name: Wait for API server on master to become reachable
  shell: |
    timeout 60 bash -c '
      until curl -k https://{{ ansible_host }}:6443/ping; do
        sleep 3;
      done'
  changed_when: false

- name: Check if kubeconfig points to the right server
  shell: grep -q "{{ ansible_host }}" /etc/rancher/k3s/k3s.yaml
  register: kubeconfig_check
  failed_when: false
  changed_when: kubeconfig_check.rc != 0

- name: Update kubeconfig server IP
  shell: >
    kubectl config set-cluster default --server=https://{{ ansible_host }}:6443 --kubeconfig=/etc/rancher/k3s/k3s.yaml
  when: kubeconfig_check.rc != 0

- name: Check if KUBECONFIG profile file exists
  stat:
    path: /etc/profile.d/kubeconfig.sh
  register: kubeconfig_profile_file

- name: Check if KUBECONFIG is already set
  shell: grep -q 'KUBECONFIG=/etc/rancher/k3s/k3s.yaml' /etc/profile.d/kubeconfig.sh
  register: kubeconfig_already_set
  changed_when: false
  failed_when: false
  when: kubeconfig_profile_file.stat.exists

- name: Set KUBECONFIG globally for vagrant user
  copy:
    content: 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml'
    dest: /etc/profile.d/kubeconfig.sh
    mode: '0644'
  when: not kubeconfig_profile_file.stat.exists or kubeconfig_already_set.rc != 0